# Generated by Django 4.2.2 on 2023-06-12 14:13

from django.db import migrations, models
import django.db.models.manager
import siteapps.posts.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('image', models.ImageField(null=True, upload_to=siteapps.posts.models.upload_img_name)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('P', 'Published'), ('D', 'Draft')], default='D', max_length=1)),
            ],
            managers=[
                ('articles', django.db.models.manager.Manager()),
            ],
        ),
    ]
